# Generated by Django 4.2.4 on 2023-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelusers',
            name='fullname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
